#!/usr/bin/env python3
"""Regenerate checklists/README.md with current item counts."""
import os, io

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)

GROUPS = [
    ("checklists/core", "core", "Core — applies to any stack",
     "Language- and framework-independent. If you build with Python, Go, Ruby, PHP, Java "
     "or anything else, this is your checklist."),
    ("checklists/ai", "ai", "AI & agent security",
     "For any product that ships an LLM feature, an agent, tool calling, RAG, or MCP. "
     "Stack-agnostic — it does not matter which model provider you use."),
    ("checklists/vibe-coding", "vibe-coding", "Vibe coding — bugs AI assistants write",
     "Organized by class of bug, not by which assistant produced it. Written from real "
     "review findings on AI-generated code."),
    ("checklists/stacks", "stacks", "Stack supplements — only if you use them",
     "The small remainder that genuinely depends on a specific product. **Skip any file "
     "for a product you do not use** — the core checklists stand on their own."),
]


def count(p):
    return sum(1 for l in open(p, encoding="utf-8") if l.startswith("* [ ] "))


def title(p):
    return open(p, encoding="utf-8").readline().lstrip("# ").strip()


def main():
    out = io.StringIO()
    w = out.write
    w("<!-- generated by scripts/build_index.py — do not edit by hand -->\n")
    w("# Checklists\n\n[← back to repository](../README.md)\n\n")
    w("Every checklist is a standalone Markdown file. Copy the ones you need into your own "
      "repo and edit them there — they are meant to be committed alongside your code.\n\n")

    counts = {}
    for folder, rel, _, _ in GROUPS:
        counts[rel] = sum(count(os.path.join(folder, f)) for f in os.listdir(folder)
                          if f.endswith(".md") and f not in ("README.md", "_TEMPLATE.md"))
    grand = sum(counts.values())
    agnostic = grand - counts["stacks"]
    w(f"**{agnostic:,} of the {grand:,} items ({round(100*agnostic/grand)}%) are "
      f"stack-agnostic** — everything outside `stacks/`. Only {counts['stacks']} items "
      "name a specific product.\n\n")

    totals = {}
    for folder, rel, head, blurb in GROUPS:
        rows, tot = [], 0
        for f in sorted(os.listdir(folder)):
            if not f.endswith(".md") or f in ("README.md", "_TEMPLATE.md"):
                continue
            p = os.path.join(folder, f)
            n = count(p)
            tot += n
            rows.append(f"| [{title(p)}]({rel}/{f}) | {n} |")
        totals[rel] = tot
        w(f"---\n\n## {head}\n\n{blurb}\n\n")
        w("| Checklist | Items |\n| --- | ---: |\n")
        w("\n".join(rows))
        w(f"\n| **Total** | **{tot:,}** |\n\n")

    w("---\n\n## Don't see your stack?\n\n"
      "The core checklists were built to work without any stack file at all. To add one "
      "for Django, Rails, Laravel, Go, AWS, Vercel, Fly.io, Android or anything else, "
      "copy [`stacks/_TEMPLATE.md`](stacks/_TEMPLATE.md) and open a pull request. "
      "See [CONTRIBUTING.md](../CONTRIBUTING.md).\n")

    open("checklists/README.md", "w", encoding="utf-8").write(out.getvalue())
    print("checklists/README.md:", {k: v for k, v in totals.items()},
          "grand total:", sum(totals.values()))


if __name__ == "__main__":
    main()
