#!/usr/bin/env python3
"""Concatenate every checklist into ALL.md — one file to paste into an AI tool or print."""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)

ORDER = ["core", "ai", "vibe-coding", "stacks"]
GROUP_TITLE = {
    "core": "Core — applies to any stack",
    "ai": "AI & agent security",
    "vibe-coding": "Vibe coding — bugs AI assistants write",
    "stacks": "Stack supplements",
}

parts = [
    "<!-- generated by scripts/build_single_file.py — do not edit by hand -->",
    "# Pre-Production Security Checklist — complete",
    "",
    "Every checklist in this repository, concatenated. Generated file — edit the "
    "individual checklists under `checklists/`, then run `./scripts/build.sh`.",
    "",
    "Source: https://github.com/FarzamHabibi/pre-production-checklist",
    "",
]

total = 0
for group in ORDER:
    folder = os.path.join("checklists", group)
    parts += ["", "---", "", f"# {GROUP_TITLE[group]}", ""]
    for f in sorted(os.listdir(folder)):
        if not f.endswith(".md") or f in ("README.md", "_TEMPLATE.md"):
            continue
        raw = open(os.path.join(folder, f), encoding="utf-8").read().split("\n")
        total += sum(1 for l in raw if l.startswith("* [ ] "))
        for l in raw:
            if l.startswith("[← all checklists]"):
                continue
            # ALL.md sits at the repo root, so ../foo/bar.md must become checklists/foo/bar.md
            l = l.replace("](../", "](checklists/")
            parts.append("#" + l if l.startswith("# ") else l)  # demote file titles
        parts.append("")

open("ALL.md", "w", encoding="utf-8").write("\n".join(parts).rstrip() + "\n")
print(f"ALL.md written — {total:,} items")
