#!/usr/bin/env python3
"""Concatenate every checklist into ALL.md — one file to paste into an AI tool or print."""
import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)
sys.path.insert(0, os.path.join(ROOT, "scripts"))
import tree  # noqa: E402

parts = [
    "<!-- generated by scripts/build_single_file.py — do not edit by hand -->",
    "# Pre-Production Checklist — complete",
    "",
    "Every checklist in this repository, concatenated. Generated file — edit the "
    "individual checklists under `checklists/`, then run `./scripts/build.sh`.",
    "",
    "Source: https://github.com/FarzamHabibi/pre-production-checklist",
    "",
]

total = 0


def emit(path, depth):
    """Append one checklist, demoting its headings and rebasing its links."""
    global total
    raw = open(path, encoding="utf-8").read().split("\n")
    total += sum(1 for l in raw if l.startswith("* [ ] "))
    here = os.path.dirname(path)
    for l in raw:
        if l.startswith("[← all checklists]") or l.startswith("[← back to repository]"):
            continue
        # ALL.md sits at the repo root, so every relative link is rebased to repo-root form
        def rebase(m):
            target = os.path.normpath(os.path.join(here, m.group(1)))
            return "](" + target.replace(os.sep, "/")
        l = re.sub(r"\]\((?!https?:|mailto:|#)([^)]+\.md)", rebase, l)
        parts.append("#" * depth + l if l.startswith("# ") else l)
    parts.append("")


for d in tree.domains():
    parts += ["", "---", "", f"# {tree.DOMAIN_LABEL[d]}", "", tree.DOMAIN_BLURB[d], ""]
    for a in tree.areas(d):
        if a:
            parts += ["", f"## {tree.AREA_LABEL.get(a, a)}", ""]
        for path, _ in tree.files(d, a):
            emit(path, 2 if a else 1)

parts += ["", "---", "", "# Stack supplements", ""]
for path, _ in tree.stack_files():
    emit(path, 1)

open("ALL.md", "w", encoding="utf-8").write("\n".join(parts).rstrip() + "\n")
print(f"ALL.md written — {total:,} items")
