#!/usr/bin/env bash
# Rasterise site-assets/og.svg to og.png (1200x630) for social previews.
# The SVG is generated by build_site.py from the live counts; this only rasterises it.
# Needs Chrome or Chromium locally; CI uses the committed PNG.
set -euo pipefail
cd "$(dirname "$0")/.."
for c in "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" \
         "$(command -v chromium || true)" "$(command -v google-chrome || true)"; do
  if [ -n "$c" ] && [ -x "$c" ]; then
    "$c" --headless --disable-gpu --hide-scrollbars \
         --screenshot="$PWD/site-assets/og.png" --window-size=1200,630 \
         "file://$PWD/site-assets/og.svg" >/dev/null 2>&1
    echo "site-assets/og.png regenerated"; exit 0
  fi
done
echo "no Chrome found — og.png left as committed" >&2
