#!/usr/bin/env python3
"""Regenerate checklists/README.md — the index, organised by domain."""
import io, json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)
sys.path.insert(0, os.path.join(ROOT, "scripts"))
import tree  # noqa: E402


def count(path):
    return sum(1 for l in open(path, encoding="utf-8") if l.startswith("* [ ] "))


def main():
    doc = json.load(open("data/checklist.json", encoding="utf-8"))
    out = io.StringIO()
    w = out.write

    w("<!-- generated by scripts/build_index.py — do not edit by hand -->\n")
    w("# Checklists\n\n[← back to repository](../README.md)\n\n")
    w("Every checklist is a standalone Markdown file. Copy the ones you need into your own "
      "repo and edit them there — they are meant to be committed alongside your code.\n\n")

    c = doc["counts"]
    w(f"**{c['total']:,} items** · {c['stack_agnostic']:,} of them "
      f"({round(100 * c['stack_agnostic'] / c['total'])}%) name no product at all.\n\n")

    w("| Domain | Items | |\n| --- | ---: | --- |\n")
    for d in tree.domains():
        n = doc["counts"]["by_domain"].get(d, 0)
        w(f"| [**{tree.DOMAIN_LABEL[d]}**](#{d}) | {n:,} | {tree.DOMAIN_BLURB[d]} |\n")
    stack_n = sum(1 for i in doc["items"] if i["stack"] != "any")
    w(f"| [Stack supplements](#stack-supplements) | {stack_n:,} | "
      f"{len(doc['stacks'])} products, only if you use them |\n\n")

    for d in tree.domains():
        w(f"---\n\n<a id=\"{d}\"></a>\n\n## {tree.DOMAIN_LABEL[d]}\n\n{tree.DOMAIN_BLURB[d]}\n\n")
        for a in tree.areas(d):
            rows, tot = [], 0
            for path, _ in tree.files(d, a):
                n = count(path)
                tot += n
                rel = path[len("checklists/"):]
                rows.append(f"| [{tree.title_of(path)}]({rel}) | {n} |")
            if a:
                w(f"### {tree.AREA_LABEL.get(a, a)}\n\n{tree.AREA_BLURB.get(a, '')}\n\n")
            w("| Checklist | Items |\n| --- | ---: |\n")
            w("\n".join(rows))
            w(f"\n| **Total** | **{tot:,}** |\n\n")

    w("---\n\n<a id=\"stack-supplements\"></a>\n\n## Stack supplements\n\n")
    w("The small remainder that genuinely depends on a specific product. **Skip any file "
      "for a product you do not use** — the domain checklists stand on their own.\n\n")
    w("One file per product, spanning every domain: each section says which checklist it "
      "extends, and items inherit that checklist's domain.\n\n")
    w("| Product | Items |\n| --- | ---: |\n")
    tot = 0
    for path, _ in tree.stack_files():
        n = count(path)
        tot += n
        w(f"| [{tree.title_of(path)}]({path[len('checklists/'):]}) | {n} |\n")
    w(f"| **Total** | **{tot:,}** |\n\n")

    w("---\n\n## Don't see your stack?\n\n"
      "The domain checklists were built to work without any stack file at all. To add one, "
      "copy [`stacks/_TEMPLATE.md`](stacks/_TEMPLATE.md) and open a pull request. "
      "See [CONTRIBUTING.md](../CONTRIBUTING.md).\n")

    open("checklists/README.md", "w", encoding="utf-8").write(out.getvalue())
    print("checklists/README.md — " + ", ".join(
        f"{d} {doc['counts']['by_domain'].get(d, 0):,}" for d in tree.domains())
        + f", stacks {stack_n:,}")


if __name__ == "__main__":
    main()
